#!/usr/bin/env python3

from yadata import Datadir

ddir=Datadir('data')
for p in ddir:
    p_other=dict(p)
    p_other['counter']+=1
    bounced=ddir.merge(p_other,{"counter":"set"})
    if bounced:
        print('bounced:',bounced)
    print('new_value:',p)


