#!/usr/bin/env python3

from yadata import Record
from yadata import Datadir
from yadata import YadataRecord 
import sys

@YadataRecord
class Person(Record):

    yadata_tag='!Person'

    @classmethod
    def is_my_type(cls,d):
        return 'name' in d and 'surname' in d

    def __eq__(self,other):

        return self['name']==other['name'] and self['surname']==other['surname']

    def get_key_prefix(self):

        return self['surname'].lower()

    subdir = 'Person'


ddir=Datadir('data')
for p in ddir:
    print(p)
    p['counter']+=1
    p.save(ddir)

