#!/usr/bin/env python3

import sys
import argparse

import yadata.command.read
import yadata.command.append

c_map={
    "read":yadata.command.read.Read,
    "append":yadata.command.append.Append,
}

parse=argparse.ArgumentParser()
subparsers=parse.add_subparsers(dest="command",help="The yacite subcommand you want to run")
subparsers.required=True
for cmd in c_map:
    cmd_class=c_map[cmd]
    subpar=subparsers.add_parser(cmd,help=cmd_class.__doc__)
    cmd_class.add_arguments(subpar)
ns=parse.parse_args()
command=c_map[ns.command](ns)
command.execute()





